const translations = {
  "es": {
    "Inicio": "Inicio",
    "sobreNosotros": "Sobre Nosotros",
    "Servicios": "Servicios",
    "SuministrosElectricos": "Suministros Eléctricos",
    "TelefoniaMovil": "Telefonía Movil",
    "ServiciosInmoviliarios": "Servicios Inmoviliarios",
    "PanelesSolares": "Paneles Solares",
    "Contacto": "Contacto",
    "somos numero uno": "Somos #1",
    "ASESORÍA ENERGÉTICA": "Servicio de Gestion Energética en la costa del sol",
    "Explorar Más": "Explorar Más",
    "Somos Tu Solución": "Somos Tu Solución",
    "Explorar más": "Explorar más",
    "Previous": "Previous",
    "Next": "Next",
    "somosLideresEnConfianza": "Somos Lideres en Confianza",
    "teAsesoramos": "te asesoramos y solucionamos cualquier tipo de inconveniente",
    "diez": "10",
    "añosDe": "años de ",
    "experiencia": "Experiencia",
    "serviciosYComunicaciones": "ENERGÍA, GAS, ALARMAS Y TELECOMUNICACIONES",
    "reparaciones": "REPARACIONES",
    "energiasRenovables": "ENERGIAS RENOVABLES",
    "gestionIntegral": "GESTION INTEGRAL",
    "puntosderecarga":"PUNTOS DE RECARGA",
    "alarmaAdt":"ALARMAS ADT",
    "asesoramientoInmoviliario": "ACESORAMIENTO INMOBILIARIO",
    "seguros":"SEGUROS",
    "telecomunicaciones":"TELECOMUNICACIONES",
    "envianosEmail": "Envianos un email",
    "llamanos": "Llamanos",
    "añosDeExperiencia": "Años de experiencia",
    "agentesComerciales": "Agentes Comerciales",
    "clientesSatisfechos": "Clientes Satisfechos",
    "proyectosFinalizados": "Proyectos Finalizados",
    "nuestrasGestiones":"Nuestras Gestiones",
    "Asesoramientos":"Asesoramientos",
    "porqueElegirnos": "Porqué elegirnos?!",
    "algunasRazones": "Algunas razones de porqué nos eligen...",
    "confianzaEficiencia": "Nuestra confianza, eficiencia y eficacia nos hacen únicos. Amamos nuestro trabajo y estamos aquí para ayudarte a alcanzar tus metas...",
    "agentesExperiencia": "Agentes con experiencia",
    "tramiteCostoBajo": "Nuestros agentes resuelven cualquier tramite en el menor tiempo posible con los costos más bajos",
    "serviciosAltaCalidad": "Servicios de alta calidad",
    "serviciosAltaCalidadDescripcion": "Trabajamos con absoluto profesionalismo, llevando nuestras soluciones al máximo nivel de eficiencia.",
    "soporte247": "24/7 Servicio al Cliente",
    "soporte247Descripcion": "Podrás comunicarte personalmente y de manera constante con tu asesor. Siempre tendrás alguien atento para ayudarte.",
    "youtubeVideo": "Youtube Video",
    "nuestrosServicios": "Nuestros Servicios",
    "mejoresServiciosIndustria": "Proveemos los mejores servicios de la Industria",
    "serviciosHogar": "Servicios para el hogar",
    "planesNecesidades": "Las tarifas que mejor se ajustan a tus necesidades",
    "conocerMas": "Conocer más...",
    "energiaRenovables": "Fuentes de energía Renovables.",
    "asesoramientoPaneles": "Estudio de viabilidad, instalación, certificación y control.",
    "instalacionesComerciales": "Servicios para empresas y comunidades",
    "asesoramientoIndustria": "Asesoramiento integral para todo tipo de industria y comercio.",
    "nuestrosProyectos": "Nuestros Proyectos...",
    "autoEngineering": "Auto Engineering",
    
    "bateriasvirtuales":"Baterias Virtuales",
    "auditoriaenergetica":"Auditorias Energéticas",
    "altasymodificaciones":"Altas y Modificaciones",
    "gestiondeincidencias":"Gestión de Incidencias",
    "estudiodereactivas":"Estudio de Energías reactivas",
    "nuestroStaff": "Nuestro Staff",
    "miembrosDedicados": "Miembros dedicados del equipo",
    "testimonios": "Testimonial",
    "queDicenClientes": "Que dicen nuestros clientes!",
    "nuestraOficina": "Nuestra Oficina",
    "direccion": "Av. Cdad. de Melilla, 24, 29631 Benalmádena, Málaga",
    "telefono": "+34 681 96 67 29",
    "email": "seycom@seycom.com",
    "enlacesRapidos": "Enlaces Rapidos",
    "terminosCondiciones": "Terminos y Condiciones",
    "soporte": "Soporte",
    "horarioAtencion": "Horario de Atención",
    "lunesJueves": "Lunes - Jueves",
    "viernes": "Viernes",
    "sabadosDomingos": "Sabados y Domingos",
    "cerrado": "Cerrado",
    "copyright": "Copyright",
    "designedBy": "Designed By",
    "mainTitle": "Colaboramos con las principales comercializadoras de LUZ y GAS.",
    "shortDescription": "Colaboramos con las principales comercializadoras de luz y gas del país, asegurando que recibas un servicio de calidad excepcional.",
    "longDescription": "Confía en nosotros para gestionar cada una de tus necesidades energéticas de la forma más eficiente.",
    "subtitle": "¿Cómo solicitar el servicio?",
   "parrafo1title": "Mándanos la factura del servicio.",
   "parrafo1description": "Puedes contactarte por WhatsApp o por cualquiera de los medios que figuran en la página para enviarnos tu factura de luz o gas, y nos encargamos de buscar la manera de reducir tus costos. Brindamos resultados asegurados, tangibles y significativos.",
      "parrafo2title": "Estudio Personalizado Dentro de las 24 horas.",
        "parrafo2description": "Nuestros asesores se asegurarán de ajustar al máximo la eficiencia en función de tus necesidades de consumo, dándole siempre prioridad a tu ahorro.",
      "parrafo3title": "Modificaciones de Suministros.",
        "parrafo3description": "SEYCOM gestiona absolutamente todo sin que se interrumpa tu acceso a la corriente eléctrica.",


        "section1part1": "#1",
          "section1part2": "Asesoría Energética",
      
      "section2part1": "EN COSTA DEL SOL",
      
      "section3part1": "Líderes en asesoramiento",
      "section3part2": "energético para tu hogar",
      "section4part1": "Proyectos solares para",
          "section4part2": "Empresas y comunidades",
      "section5part1": "Puntos de",
          "section5part2": "recarga para",
          "section5part3": "vehículos",
      
      "section6part1": "Ofrecemos soluciones a medida que maximizan",
          "section6part2": "la eficiencia energética y los ahorros",
      "section7part1": "Compromiso con la",
          "section7part2": "sostenibilidad",
      "section8part1": "Tu asesor energético"
      

  },
  "en": {
    "Inicio": "Home",
    "sobreNosotros": "About Us",
    "Servicios": "Services",
    "SuministrosElectricos": "Electric Supplies",
    "TelefoniaMovil": "Mobile Telephony",
    "ServiciosInmoviliarios": "Real Estate Services",
    "PanelesSolares": "Solar Panels",
    "Contacto": "Contact",
    "somos numero uno": "We Are #1",
    "ASESORÍA ENERGÉTICA": "ENERGY CONSULTING",
    "Explorar Más": "Explore More",
    "Somos Tu Solución": "We Are Your Solution",
    "Explorar más": "Explore more",
    "Previous": "Previous",
    "Next": "Next",
    "somosLideresEnConfianza": "We Are Leaders in Trust",
    "teAsesoramos": "We advise you and solve any type of inconvenience",
    "diez": "10",
    "añosDe": "years of ",
    "experiencia": "Experience",
    "serviciosYComunicaciones": "ENERGY, GAS, ALARMS & TELECOMUNICATIONS",
    "reparaciones": "REPAIRS",
    "energiasRenovables": "RENEWABLE ENERGIES",
    "gestionIntegral": "INTEGRAL MANAGMENT",
    "asesoramientoInmoviliario": "REAL STATE CONSULTING",
    "envianosEmail": "Send us an email",
    "llamanos": "Call us",
    "añosDeExperiencia": "Years of experience",
    "agentesComerciales": "Commercial Agents",
    "clientesSatisfechos": "Satisfied Clients",
    "proyectosFinalizados": "Completed Projects",
    "porqueElegirnos": "Why choose us?!",
    "algunasRazones": "Some reasons why they choose us...",
    "confianzaEficiencia": "Our trust, efficiency and effectiveness make us unique. We love our work and we are here to help you achieve your goals...",
    "agentesExperiencia": "Experienced agents",
    "tramiteCostoBajo": "Our agents resolve any procedure in the shortest possible time with the lowest costs",
    "serviciosAltaCalidad": "High-quality services",
    "serviciosAltaCalidadDescripcion": "We work with absolute professionalism, delivering our solutions with maximum efficiency.",
    "soporte247": "24/7 Customer Support",
    "soporte247Descripcion": "You will be able to communicate personally and constantly with your advisor. You will always have someone attentive to help you.",
    "youtubeVideo": "Youtube Video",
    "nuestrosServicios": "Our Services",
    "mejoresServiciosIndustria": "We provide the best services in the Industry",
    "serviciosHogar": "Home Services",
    "planesNecesidades": "Plans that best suit your needs",
    "conocerMas": "Learn more...",
    "energiaRenovables": "Renewable Energy Sources.",
    "asesoramientoPaneles": "Feasibility study, installation, certification and control.",
    "instalacionesComerciales": "Services for businesses and communities",
    "asesoramientoIndustria": "Consulting for all types of industry and commerce.",
    "nuestrosProyectos": "Our Projects...",
    "autoEngineering": "Auto Engineering",
    "nuestrasGestiones":"Our Effort..",
    "Asesoramientos":"Advice...",
    "civilEngineering": "Civil Engineering",
    "gasEngineering": "Gas Engineering",
    "powerEngineering": "Power Engineering",
    "energyEngineering": "Energy Engineering",
    "waterEngineering": "Water Engineering",
    "nuestroStaff": "Our Staff",
    "miembrosDedicados": "Dedicated team members",
    "testimonios": "Testimonial",
    "queDicenClientes": "What our clients say!",
    "nuestraOficina": "Our Office",
    "direccion": "Av. Cdad. de Melilla, 24, 29631 Benalmádena, Málaga",
    "telefono": "+34 681 96 67 29",
    "email": "seycom@seycom.com",
    "enlacesRapidos": "Quick Links",
    "terminosCondiciones": "Terms and Conditions",
    "soporte": "Support",
    "horarioAtencion": "Opening Hours",
    "lunesJueves": "Monday - Thursday",
    "viernes": "Friday",
    "sabadosDomingos": "Saturday and Sunday",
    "cerrado": "Closed",
    "copyright": "Copyright",
    "designedBy": "Designed By",
    "mainTitle": "We collaborate with the leading national light and gas companies.",
    "shortDescription": "We collaborate with the leading light and gas marketers in the country, ensuring you receive excellent quality and comfort service.",
    "longDescription": "Trust us to manage all your energy needs in the most efficient way.",
    "subtitle": "How to request the service?",
    "parrafo1title": "Send us your service bill.",
        "parrafo1description": "You can contact us via WhatsApp or any of the means listed on the page to send us your light or gas bill, and we will look for ways to reduce your costs. We provide guaranteed, tangible, and significant results.",
      "parrafo2title": "Personalized Study Within 24 hours.",
        "parrafo2description": "Our advisors will ensure maximum efficiency tailored to your consumption needs, always prioritizing your savings.",
      
        "parrafo3title": "Supply Modifications.",
        "parrafo3description": "SEYCOM manages everything without interrupting your access to electricity.",
  
  "section1part1": "#1",
  "section1part2": "Energy Consultancy",

"section2part1": "EN COSTA DEL SOL",

"section3part1": "Leaders in energy consultancy",
"section3part2": "for your home",
"section4part1": "Solar projects for",
            "section4part2": "Companies and communities",
"section5part1": "Charging points for",
  "section5part2": "vehicles",
  "section5part3": "",

"section6part1": "We offer tailored solutions that maximize",
  "section6part2": "energy efficiency and savings",
"section7part1": "Commitment to",
  "section7part2": "sustainability",
"section8part1": "Your energy advisor"
  }
};
